class_name KayKitPaths
## res:// paths to the KayKit assets (generated by asset prep).

const CHARACTERS: Array[String] = [
	"res://assets/kaykit/characters/Knight.glb",
	"res://assets/kaykit/characters/Barbarian.glb",
	"res://assets/kaykit/characters/Mage.glb",
	"res://assets/kaykit/characters/Rogue.glb",
	"res://assets/kaykit/characters/Ranger.glb",
	"res://assets/kaykit/characters/Rogue_Hooded.glb",
]
const BLOCK_GRASS := "res://assets/kaykit/blocks/dirt_with_grass.gltf"
const BLOCK_DIRT := "res://assets/kaykit/blocks/dirt.gltf"
const BLOCK_DIRT_DARK := "res://assets/kaykit/blocks/gravel.gltf"
const BLOCK_BEDROCK := "res://assets/kaykit/blocks/bricks_A.gltf"
const BLOCK_GOLD := "res://assets/kaykit/blocks/colored_block_yellow.gltf"
const BLOCK_WOOD := "res://assets/kaykit/blocks/wood.gltf"
